#!/usr/bin/env bash

# SPDX-FileLicenseText: 2024 Thomas Lehmann <t.lehmann@strato.de>
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

CONTAINER_NAME="nc-simplesettings-dev"
CODE_DIR_IN_CONTAINER="/app"

function main() {
	local container_dir="$( readlink -f "$( dirname "${0}" )" )"
	local image_name="localhost/${CONTAINER_NAME}:latest"
	local repo_root_dir="$( pwd )"

	podman image build \
		-f ${container_dir}/Containerfile \
		-t ${image_name} \
			${container_dir}

	if [ ${?} -ne 0 ]; then
		echo "Error building the image."
		exit 1
	fi

	echo "Run ${image_name} as ${CONTAINER_NAME} ..."

	podman run \
		--network=host \
		--rm \
		-it \
		--env "CONTAINER_NAME=${CONTAINER_NAME}" \
		--name ${CONTAINER_NAME} \
		--workdir "${CODE_DIR_IN_CONTAINER}" \
		--mount "type=bind,source=${repo_root_dir},target=${CODE_DIR_IN_CONTAINER}" \
			"${image_name}" \
				"${@}"
}

main "${@}"
